
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef VCU_OBJDICT_H
#define VCU_OBJDICT_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 VCU_valueRangeTest (UNS8 typeValue, void * value);
const subindex * VCU_scanIndexOD (UNS16 wIndex, UNS8 *size, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data VCU_Data;

#endif // VCU_OBJDICT_H
