
/* File generated by gen_cfile.py. Should not be modified. */

#include "VCU_ObjDict.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x24 /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 VCU_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 VCU_bDeviceNodeId = 0x11;

/**************************************************************************/
/* Array of message processing information */

const UNS8 VCU_iam_a_slave = 0;

TIMER_HANDLE VCU_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 VCU_obj1000 = 0x0;	/* 0 */
                    subindex VCU_Index1000[] = 
                     {
                       { RO, CANopen_TYPE_uint32, (void*)&VCU_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 VCU_obj1001 = 0x0;	/* 0 */
                    subindex VCU_Index1001[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&VCU_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 VCU_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 VCU_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t VCU_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex VCU_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&VCU_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&VCU_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS16 VCU_obj1005 = 0x0;	/* 0 */
                    ODCallback_t VCU_Index1005_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex VCU_Index1005[] = 
                     {
                       { RW, CANopen_TYPE_uint16, (void*)&VCU_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 VCU_obj1006 = 0x0;	/* 0 */
                    ODCallback_t VCU_Index1006_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex VCU_Index1006[] = 
                     {
                       { RW, CANopen_TYPE_uint32, (void*)&VCU_obj1006 }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 VCU_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 VCU_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 VCU_obj1014 = 0x80 + 0x11;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 VCU_highestSubIndex_obj1016 = 0;
                    UNS32 VCU_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 VCU_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 VCU_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 VCU_obj1018_Vendor_ID = 0x11;	/* 17 */
                    UNS32 VCU_obj1018_Product_Code = 0x11;	/* 17 */
                    UNS32 VCU_obj1018_Revision_Number = 0x1;	/* 1 */
                    UNS32 VCU_obj1018_Serial_Number = 0x11;	/* 17 */
                    subindex VCU_Index1018[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&VCU_highestSubIndex_obj1018 },
                       { RO, CANopen_TYPE_uint32, (void*)&VCU_obj1018_Vendor_ID },
                       { RO, CANopen_TYPE_uint32, (void*)&VCU_obj1018_Product_Code },
                       { RO, CANopen_TYPE_uint32, (void*)&VCU_obj1018_Revision_Number },
                       { RO, CANopen_TYPE_uint32, (void*)&VCU_obj1018_Serial_Number }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 VCU_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS16 VCU_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x611;	/* 1553 */
                    UNS16 VCU_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x581;	/* 1409 */
                    UNS8 VCU_obj1280_Node_ID_of_the_SDO_Server = 0x1;	/* 1 */
                    subindex VCU_Index1280[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&VCU_highestSubIndex_obj1280 },
                       { RW, CANopen_TYPE_uint16, (void*)&VCU_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, CANopen_TYPE_uint16, (void*)&VCU_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, CANopen_TYPE_uint8, (void*)&VCU_obj1280_Node_ID_of_the_SDO_Server }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const subindex * VCU_scanIndexOD (UNS16 wIndex, UNS8 *size, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	subindex *si= NULL;
	switch(wIndex){
		case 0x1000: si = VCU_Index1000; *size= sizeof(VCU_Index1000)/sizeof(VCU_Index1000[0]); break;
		case 0x1001: si = VCU_Index1001; *size= sizeof(VCU_Index1001)/sizeof(VCU_Index1001[0]); break;
		case 0x1005: si = VCU_Index1005; *size= sizeof(VCU_Index1005)/sizeof(VCU_Index1005[0]); *callbacks = VCU_Index1005_callbacks; break;
		case 0x1006: si = VCU_Index1006; *size= sizeof(VCU_Index1006)/sizeof(VCU_Index1006[0]); *callbacks = VCU_Index1006_callbacks; break;
		case 0x1018: si = VCU_Index1018; *size= sizeof(VCU_Index1018)/sizeof(VCU_Index1018[0]); break;
		case 0x1280: si = VCU_Index1280; *size= sizeof(VCU_Index1280)/sizeof(VCU_Index1280[0]); break;
		default:
			return NULL;
	}
	return si;
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status VCU_PDO_status[1] = {s_PDO_status_Initializer};

CO_Data VCU_Data = CANOPEN_NODE_DATA_INITIALIZER(VCU);

UNS8 ObjDict_DataSize(const subindex *s) {
  if(s->bDataType==valueRange_EMC) return 1;
  else return 0;
}

